"""Genomic LSTM trading strategy with risk management.

Provides:
- ``SignalEnum`` — LONG / SHORT / HOLD signal constants
- ``GenomicTradingStrategy`` — LSTM-based strategy with position sizing
- ``BuyAndHoldStrategy`` — passive baseline always holding long
- ``GARCHStrategy`` — volatility-forecast-driven signal strategy
"""

from __future__ import annotations

import logging
from enum import Enum
from typing import Any, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Signal enum
# ---------------------------------------------------------------------------


class SignalEnum(Enum):
    """Directional trading signal."""

    LONG = 1
    SHORT = -1
    HOLD = 0


# ---------------------------------------------------------------------------
# Genomic LSTM strategy
# ---------------------------------------------------------------------------


class GenomicTradingStrategy:
    """Trading strategy driven by a trained Genomic LSTM model.

    The model predicts the probability of a market "spike" (large up move)
    or "crash" (large down move) over the coming period.  Signals are
    generated by thresholding these probabilities.

    Parameters
    ----------
    model_trainer:
        A fitted model trainer object that exposes a
        ``predict_proba(context_window)`` method returning an array of shape
        ``(n_classes,)`` with per-class probabilities.  The contract assumed
        here is that the first two output nodes correspond to crash / spike
        probabilities (depends on the discretisation mapping used by the
        trainer).
    spike_threshold:
        Minimum spike probability required to generate a LONG signal.
    crash_threshold:
        Minimum crash probability required to generate a SHORT signal.
    position_sizing:
        Default position-sizing method.  One of ``'fixed'``, ``'kelly'``,
        or ``'volatility'``.
    """

    def __init__(
        self,
        model_trainer: Any,
        spike_threshold: float = 0.70,
        crash_threshold: float = 0.70,
        position_sizing: str = "fixed",
    ) -> None:
        if not 0.0 < spike_threshold <= 1.0:
            raise ValueError(f"spike_threshold must be in (0, 1], got {spike_threshold}")
        if not 0.0 < crash_threshold <= 1.0:
            raise ValueError(f"crash_threshold must be in (0, 1], got {crash_threshold}")
        if position_sizing not in {"fixed", "kelly", "volatility"}:
            raise ValueError(
                f"position_sizing must be 'fixed', 'kelly', or 'volatility', got {position_sizing}"
            )

        self.model_trainer = model_trainer
        self.spike_threshold = spike_threshold
        self.crash_threshold = crash_threshold
        self.position_sizing = position_sizing

    # ------------------------------------------------------------------
    # Signal generation
    # ------------------------------------------------------------------

    def generate_signal(self, context_window: Any) -> SignalEnum:
        """Generate a trading signal from the model's prediction.

        Parameters
        ----------
        context_window:
            Input feature array / tensor accepted by
            ``self.model_trainer.predict_proba``.  Shape depends on the
            model architecture (typically ``(seq_len, n_features)``).

        Returns
        -------
        SignalEnum
            LONG, SHORT, or HOLD.
        """
        try:
            probs = self.model_trainer.predict_proba(context_window)
            probs = np.asarray(probs, dtype=float).ravel()
        except Exception as exc:
            logger.warning("Model prediction failed: %s — returning HOLD", exc)
            return SignalEnum.HOLD

        if len(probs) < 2:
            logger.warning("Model returned fewer than 2 probability outputs — returning HOLD")
            return SignalEnum.HOLD

        # Convention: index 0 = crash (SHORT), index 1 = spike (LONG)
        crash_prob = float(probs[0])
        spike_prob = float(probs[1])

        if spike_prob >= self.spike_threshold and spike_prob > crash_prob:
            return SignalEnum.LONG
        if crash_prob >= self.crash_threshold and crash_prob > spike_prob:
            return SignalEnum.SHORT
        return SignalEnum.HOLD

    # ------------------------------------------------------------------
    # Position sizing
    # ------------------------------------------------------------------

    def compute_position_size(
        self,
        signal: SignalEnum,
        portfolio_value: float,
        volatility_estimate: float,
        method: Optional[str] = None,
    ) -> float:
        """Compute the notional position size in dollars.

        Parameters
        ----------
        signal:
            Current trading signal.
        portfolio_value:
            Current total portfolio value in dollars.
        volatility_estimate:
            Annualised (or period) volatility estimate used by the
            ``'volatility'`` and ``'kelly'`` sizing methods.
        method:
            Override the instance-level sizing method.  One of ``'fixed'``,
            ``'kelly'``, or ``'volatility'``.

        Returns
        -------
        float
            Signed dollar position size.  Positive for long, negative for
            short, zero for HOLD.
        """
        if signal is SignalEnum.HOLD:
            return 0.0

        method = method or self.position_sizing
        direction = 1.0 if signal is SignalEnum.LONG else -1.0

        if method == "fixed":
            # Fixed 100 % notional (no leverage)
            size = portfolio_value

        elif method == "volatility":
            # Volatility targeting: target 10 % annualised portfolio vol
            target_vol = 0.10
            if volatility_estimate <= 0:
                logger.warning("Non-positive volatility estimate — using fixed sizing")
                size = portfolio_value
            else:
                vol_scalar = target_vol / volatility_estimate
                # Cap leverage at 2×
                size = portfolio_value * min(vol_scalar, 2.0)

        elif method == "kelly":
            # Half-Kelly: 50 % of the full Kelly fraction applied to capital
            # Uses a conservative 55 % win-rate and 1:1 payoff assumption
            # unless the model trainer exposes historical metrics
            win_rate_val = getattr(self.model_trainer, "historical_win_rate", 0.55)
            avg_win = getattr(self.model_trainer, "historical_avg_win", 1.0)
            avg_loss = getattr(self.model_trainer, "historical_avg_loss", 1.0)
            if avg_loss <= 0:
                size = portfolio_value * 0.5
            else:
                odds = avg_win / avg_loss
                loss_rate = 1.0 - win_rate_val
                full_kelly = win_rate_val - (loss_rate / odds)
                half_kelly = max(0.0, full_kelly * 0.5)
                size = portfolio_value * half_kelly

        else:
            raise ValueError(f"Unknown position sizing method: {method!r}")

        return float(direction * size)

    # ------------------------------------------------------------------
    # Slippage
    # ------------------------------------------------------------------

    @staticmethod
    def apply_slippage(price: float, direction: int, bps: float = 1.0) -> float:
        """Adjust an execution price for market impact / slippage.

        Parameters
        ----------
        price:
            Mid or quoted price before slippage.
        direction:
            +1 for a buy (pays up), -1 for a sell (receives less).
        bps:
            Slippage in basis points (1 bp = 0.0001).

        Returns
        -------
        float
            Execution price after slippage.
        """
        if direction not in (1, -1):
            raise ValueError(f"direction must be +1 or -1, got {direction}")
        adjustment = price * bps * 1e-4 * direction
        return float(price + adjustment)


# ---------------------------------------------------------------------------
# Buy-and-hold baseline
# ---------------------------------------------------------------------------


class BuyAndHoldStrategy:
    """Passive buy-and-hold baseline: always returns a LONG signal.

    Parameters
    ----------
    None
    """

    @staticmethod
    def generate_signal(context_window: Any = None) -> SignalEnum:
        """Always return LONG regardless of market conditions.

        Parameters
        ----------
        context_window:
            Ignored.  Accepted for API compatibility.

        Returns
        -------
        SignalEnum
            Always ``SignalEnum.LONG``.
        """
        return SignalEnum.LONG


# ---------------------------------------------------------------------------
# GARCH-based strategy
# ---------------------------------------------------------------------------


class GARCHStrategy:
    """Volatility-forecast-driven strategy using a GARCH model.

    The strategy goes LONG when the forecast volatility is low (calm regime)
    and SHORT when forecast volatility is high (turbulent regime).

    Parameters
    ----------
    garch_model:
        A fitted GARCH model object that exposes a
        ``forecast(horizon, returns)`` method returning an object with a
        ``variance`` attribute (a ``(1, horizon)`` array or scalar).
    vol_long_threshold:
        Annualised forecast volatility below which a LONG signal is issued.
        Defaults to 0.15 (15 %).
    vol_short_threshold:
        Annualised forecast volatility above which a SHORT signal is issued.
        Defaults to 0.30 (30 %).
    annualization:
        Periods per year used to annualise daily variance forecasts.
    """

    def __init__(
        self,
        garch_model: Any,
        vol_long_threshold: float = 0.15,
        vol_short_threshold: float = 0.30,
        annualization: int = 252,
    ) -> None:
        self.garch_model = garch_model
        self.vol_long_threshold = vol_long_threshold
        self.vol_short_threshold = vol_short_threshold
        self.annualization = annualization

    def generate_signal(self, recent_returns: pd.Series) -> SignalEnum:
        """Generate a signal based on GARCH volatility forecast.

        Parameters
        ----------
        recent_returns:
            Recent return series used as the conditioning information set.
            Passed to ``garch_model.forecast``.

        Returns
        -------
        SignalEnum
            LONG, SHORT, or HOLD.
        """
        try:
            forecast_obj = self.garch_model.forecast(horizon=1, x=recent_returns)
            # arch library: forecast_obj.variance.iloc[-1, 0] is daily variance
            daily_var = float(np.asarray(forecast_obj.variance).ravel()[-1])
        except Exception as exc:
            logger.warning("GARCH forecast failed: %s — returning HOLD", exc)
            return SignalEnum.HOLD

        if daily_var <= 0:
            logger.warning("Non-positive variance forecast — returning HOLD")
            return SignalEnum.HOLD

        ann_vol = np.sqrt(daily_var * self.annualization)

        if ann_vol < self.vol_long_threshold:
            return SignalEnum.LONG
        if ann_vol > self.vol_short_threshold:
            return SignalEnum.SHORT
        return SignalEnum.HOLD
